name: Deploy API on Model Change

on:
  push:
    branches:
      - main  # Chạy workflow khi có thay đổi trên nhánh main

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Clone mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v3

      # Bước 2: Thiết lập Python và cài đặt thư viện
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dvc[gdrive]

      # Bước 3: Pull mô hình mới nhất từ DVC remote
      - name: Pull Model from DVC Remote
        run: |
          dvc pull models/fine_tuned_gpt2

      # Bước 4: Kiểm tra sự khác biệt trong mô hình
      - name: Check for Model Changes
        id: check_model
        run: |
          dvc diff > model_diff.txt
          if grep -q "models/fine_tuned_gpt2" model_diff.txt; then
            echo "model_changed=true" >> $GITHUB_ENV
          else
            echo "model_changed=false" >> $GITHUB_ENV

      # Bước 5: Deploy lại API nếu model thay đổi
      - name: Deploy API
        if: env.model_changed == 'true'
        run: |
          echo "Model has changed. Deploying API..."
          docker build -t gpt2-api .
          docker run -d -p 8000:8000 gpt2-api
      - name: Skip Deploy
        if: env.model_changed == 'false'
        run: echo "Model has not changed. Skipping API deployment."
