name: Deploy API on Heroku123

on:
  push:
    branches:
      - main
    # paths:
    #   - models/fine_tuned_gpt2.dvc  # Trigger chỉ khi file .dvc thay đổi

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
    # Bước 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Bước 2: Setup Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # Bước 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Create credentials.json
      run: |
        mkdir -p /tmp/credentials
        echo "${{ secrets.GDRIVE_CREDENTIALS }}" > /tmp/credentials/credentials.json

    # - name: Create credentials.json
    #   env:
    #     GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
    #   run: |
    #     mkdir -p /tmp/credentials
    #     echo "$GDRIVE_CREDENTIALS" > /tmp/credentials/credentials.json
      
      
    # Bước 4: Install Heroku CLI
    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    # Bước 5: Log in to Heroku Container Registry
    - name: Log in to Heroku Container Registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com

    - name: Set Heroku Stack  
      run: heroku stack:set container -a ${{ secrets.HEROKU_APP_NAME }}
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  
    # Bước 6: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .
        docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      # Bước 8: Release App on Heroku
    - name: Release API on Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku stack:set container -a ${{ secrets.HEROKU_APP_NAME }}
        heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}