on:
  push:
    branches:
      - main
  schedule:
    # Chạy hàng ngày lúc 2:00 sáng UTC
    - cron: "0 2 * * *"

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dvc
          pip install -r requirements.txt

      - name: Execute Pipeline Tasks
        run: |
          # Task 1: Check Data
          if [[ $(dvc status) != "Data and pipelines are up to date." ]]; then
            echo "Data has changed. Proceeding to fine-tune."
            touch proceed_to_fine_tune
          else
            echo "No changes in data. Skipping fine-tune."
          fi

          # Task 2: Fine-Tune Model
          if [[ -f "proceed_to_fine_tune" ]]; then
            echo "Fine-tuning the model..."
            python src/train_model.py
            dvc add models/fine_tuned_gpt2
            git add models/fine_tuned_gpt2.dvc
            git commit -m "Fine-tuned GPT-2 model updated with DVC"
            git push origin main
            dvc push
          else
            echo "Skipping fine-tune as no trigger file exists."
          fi

  deploy-api:
    needs: run-pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build and Deploy API
        run: |
          echo "Building and deploying API..."
          docker build -t gpt2-api .
          docker run -d -p 8000:8000 gpt2-api

  monitor-model:
    needs: deploy-api
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Monitor Model
        run: |
          echo "Monitoring the model..."
          python src/monitoring.py
