name: MLOps Pipeline Workflow

on:
  push:
    branches:
      - main  # Kích hoạt khi có thay đổi trên nhánh main
  pull_request:
    branches:
      - main  # Kích hoạt khi có pull request vào nhánh main
  schedule:
    - cron: "0 0 * * *"  # Chạy tự động hàng ngày vào 0h

jobs:
  run_pipeline:
    name: Run MLOps Pipeline
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v3

      # Bước 2: Thiết lập Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      # Bước 3: Cài đặt các thư viện cần thiết
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Bước 4: Thiết lập DVC và kết nối remote
      - name: Configure DVC
        run: |
          dvc remote add -d myremote gdrive://path-to-your-project
          dvc remote modify myremote gdrive_service_account_json_file_path data/ggdrive/credentials.json

      # Bước 5: Chạy pipeline Prefect
      - name: Run Prefect pipeline
        run: |
          python src/mlops_pipeline.py

      # Bước 6: Đẩy dữ liệu và mô hình lên remote storage
      - name: Push data and model to remote
        run: |
          dvc push
