name: MLOps Pipeline

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên nhánh main
  pull_request:
    branches:
      - main  # Chạy khi có pull request vào main

jobs:
  pipeline:
    name: Run MLOps Pipeline
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v3

      # Bước 2: Cài đặt Python và các thư viện
      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      # Bước 3: Chạy file pipeline.yaml
      - name: Run Pipeline
        run: |
          prefect deployment build src/pipeline.yaml:main_pipeline --name "MLOps Pipeline"
          prefect deployment apply main_pipeline-deployment.yaml
          prefect agent start
